<?php

declare(strict_types=1);

return [
    'enabled' => true,
    'mode' => 'observe',
    'trusted_proxies' => [],
    'trusted_headers' => [
        'x-forwarded-for',
        'x-real-ip',
        'forwarded',
    ],
    'allowed_methods' => [
        'GET',
        'POST',
        'PUT',
        'PATCH',
        'DELETE',
        'OPTIONS',
        'HEAD',
    ],
    'body_size_limit' => 262144,
    'detectors' => [
        'ip' => true,
        'method' => true,
        'path' => true,
        'query' => true,
        'header' => true,
        'cookie' => true,
        'body' => true,
        'ua' => true,
        'file_upload' => true,
    ],
    'decision' => [
        'score_threshold' => 70,
        'block_on_first_match' => true,
    ],
    'thresholds' => [
        'query_parameter_count' => 128,
        'body_parameter_count' => 128,
        'header_value_length' => 2048,
        'max_value_length' => 4096,
        'max_nested_depth' => 6,
        'max_scan_length' => 4096,
    ],
    'header_detection' => [
        'exclude_names' => [
            'accept',
            'accept-encoding',
            'accept-language',
            'authorization',
            'cache-control',
            'connection',
            'content-length',
            'content-type',
            'host',
            'origin',
            'pragma',
            'referer',
            'sec-ch-ua*',
            'sec-fetch-*',
            'user-agent',
            'x-forwarded-host',
        ],
    ],
    'whitelist' => [
        'ips' => [],
        'cidrs' => [],
        'paths' => [
            '/health*',
            '/metrics*',
        ],
        'routes' => [],
        'headers' => [],
        'user_agents' => [],
    ],
    'blacklist' => [
        'ips' => [],
        'cidrs' => [],
        'paths' => [],
        'routes' => [],
        'headers' => [],
        'user_agents' => [],
    ],
    'sensitive_paths' => [
        '/.env',
        '/.git/config',
        '/phpinfo.php',
        '/vendor/phpunit/phpunit/src/util/php/eval-stdin.php',
        '/actuator',
        '/wp-admin',
        '/_profiler/phpinfo',
        '/debug/default/view',
    ],
    // You may add 'curl/' or 'python-requests' here, but note they are used
    // by many legitimate API clients and may cause false positives.
    'bad_user_agents' => [
        'sqlmap',
        'acunetix',
        'nuclei',
        'masscan',
        'dirbuster',
        'nikto',
        'nessus',
        'zgrab',
    ],
    'files' => [
        'max_files' => 12,
        'max_filename_length' => 180,
        'max_total_size' => 10485760,
        'suspicious_extensions' => [
            'php',
            'phtml',
            'phar',
            'jsp',
            'jspx',
            'asp',
            'aspx',
            'cgi',
            'pl',
            'sh',
            'bash',
            'ps1',
            'exe',
        ],
        'suspicious_mime_types' => [
            'application/x-httpd-php',
            'application/x-php',
            'text/x-php',
            'application/x-sh',
            'application/x-msdownload',
            'application/x-dosexec',
        ],
    ],
    'normalizers' => [
        'url_decode_passes' => 2,
        'html_entity_decode' => true,
        'base64_probe' => true,
    ],
    'response' => [
        'status' => 403,
        'headers' => [
            'content-type' => 'application/json; charset=utf-8',
            'cache-control' => 'no-store',
        ],
        'body' => [
            'code' => 403,
            'message' => 'Request blocked by WAF.',
        ],
    ],
    'logging' => [
        'enabled' => true,
        'channel' => null,
        'body_max_length' => 2048,
        'ua_max_length' => 255,
        'matched_sample_length' => 120,
    ],
    'rules' => [
        [
            'rule_id' => 'sqli-union-select',
            'name' => 'SQL UNION SELECT probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/\\bunion\\b.{0,24}\\bselect\\b/i',
            'prefilters' => ['union', 'select'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-select-from',
            'name' => 'SQL SELECT FROM probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/\\bselect\\b.{0,24}\\bfrom\\b/i',
            'prefilters' => ['select', 'from'],
            'score' => 50,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-tautology',
            'name' => 'SQL tautology payload',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/(?:\\bor\\b|\\band\\b)\\s+[\\(\\s]*[\\\'"]?\\d+[\\\'"]?\\s*=\\s*[\\\'"]?\\d+[\\\'"]?/i',
            'prefilters' => ['or', 'and', '='],
            'score' => 45,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'xss-script-tag',
            'name' => 'Script tag payload',
            'type' => 'xss',
            'target' => 'input',
            'pattern' => '/<\\s*script\\b/i',
            'prefilters' => ['<script', '&lt;script'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'xss-event-handler',
            'name' => 'Inline event handler payload',
            'type' => 'xss',
            'target' => 'input',
            'pattern' => '/on(?:error|load|click|mouseover|focus)\\s*=\\s*/i',
            'prefilters' => ['onerror', 'onload', 'onclick', 'mouseover', 'focus'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'xss-javascript-scheme',
            'name' => 'JavaScript pseudo protocol',
            'type' => 'xss',
            'target' => 'input',
            'pattern' => '/javascript\\s*:/i',
            'prefilters' => ['javascript:'],
            'score' => 45,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'rce-shell-metachar',
            'name' => 'Shell metacharacter chain',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/(?:;|\\|\\||&&|`|\\$\\().{0,48}(?:curl|wget|bash|sh|python|perl|nc)\\b/i',
            'prefilters' => [';', '||', '&&', '`', '$(', 'curl', 'wget', 'bash', 'sh'],
            'score' => 70,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'traversal-dot-dot',
            'name' => 'Path traversal sequence',
            'type' => 'traversal',
            'target' => 'input',
            'pattern' => '/(?:\\.\\.\\/|\\.\\.\\\\\\\\|%2e%2e%2f|%252e%252e%252f)/i',
            'prefilters' => ['../', '..\\', '%2e', '%252e'],
            'score' => 65,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'lfi-sensitive-file',
            'name' => 'Sensitive local file inclusion path',
            'type' => 'lfi',
            'target' => 'input',
            'pattern' => '/(?:\\/etc\\/passwd|\\/proc\\/self\\/environ|win\\.ini)/i',
            'prefilters' => ['/etc/passwd', '/proc/self/environ', 'win.ini'],
            'score' => 75,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'ssrf-metadata',
            'name' => 'SSRF cloud metadata probe',
            'type' => 'ssrf',
            'target' => 'input',
            'pattern' => '/(?:169\\.254\\.169\\.254|metadata\\.google\\.internal|localhost(?::\\d+)?|127\\.0\\.0\\.1)/i',
            'prefilters' => ['169.254.169.254', 'metadata.google.internal', 'localhost', '127.0.0.1'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'path-sensitive-probe',
            'name' => 'Sensitive path probe',
            'type' => 'path',
            'target' => 'path',
            'pattern' => '/(?:\\.env|\\.git\\/config|phpinfo\\.php|actuator|wp-admin)/i',
            'prefilters' => ['.env', '.git/config', 'phpinfo.php', 'actuator', 'wp-admin'],
            'score' => 85,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'ua-scanner',
            'name' => 'Known scanner user agent',
            'type' => 'ua',
            'target' => 'ua',
            'pattern' => '/(?:sqlmap|acunetix|nuclei|masscan|nessus|nikto|dirbuster)/i',
            'prefilters' => ['sqlmap', 'acunetix', 'nuclei', 'masscan', 'nessus', 'nikto', 'dirbuster'],
            'score' => 65,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'header-proxy-inject',
            'name' => 'Suspicious forwarding header payload',
            'type' => 'header',
            'target' => 'header',
            'pattern' => '/(?:\\bforwarded\\b|\\bx-forwarded-for\\b).{0,24}(?:127\\.0\\.0\\.1|169\\.254\\.169\\.254)/i',
            'prefilters' => ['forwarded', 'x-forwarded-for', '127.0.0.1', '169.254.169.254'],
            'score' => 40,
            'action' => 'score',
            'enabled' => true,
        ],
    ],
];
