<?php

declare(strict_types=1);

return [
    'enabled' => true,
    'mode' => 'observe',
    'trusted_proxies' => [],
    'trusted_headers' => [
        'x-forwarded-for',
        'x-real-ip',
        'forwarded',
    ],
    'allowed_methods' => [
        'GET',
        'POST',
        'PUT',
        'PATCH',
        'DELETE',
        'OPTIONS',
        'HEAD',
    ],
    'body_size_limit' => 262144,
    'detectors' => [
        'ip' => true,
        'method' => true,
        'path' => true,
        'query' => true,
        'header' => true,
        'cookie' => true,
        'body' => true,
        'ua' => true,
        'file_upload' => true,
    ],
    'decision' => [
        'score_threshold' => 70,
        'block_on_first_match' => true,
    ],
    'thresholds' => [
        'query_parameter_count' => 128,
        'body_parameter_count' => 128,
        'header_value_length' => 2048,
        'max_value_length' => 4096,
        'max_nested_depth' => 6,
        'max_scan_length' => 4096,
    ],
    'header_detection' => [
        'exclude_names' => [
            'accept',
            'accept-encoding',
            'accept-language',
            'authorization',
            'cache-control',
            'connection',
            'content-length',
            'content-type',
            'host',
            'origin',
            'pragma',
            'sec-ch-ua*',
            'sec-fetch-*',
            'user-agent',
            'x-forwarded-host',
        ],
    ],
    'whitelist' => [
        'ips' => [],
        'cidrs' => [],
        'paths' => [
            '/health*',
            '/metrics*',
        ],
        'routes' => [],
        'headers' => [],
        'user_agents' => [],
    ],
    'blacklist' => [
        'ips' => [],
        'cidrs' => [],
        'paths' => [],
        'routes' => [],
        'headers' => [],
        'user_agents' => [],
    ],
    'sensitive_paths' => [
        '/.env',
        '/.git/config',
        '/.git/HEAD',
        '/.svn/entries',
        '/.DS_Store',
        '/.htaccess',
        '/.htpasswd',
        '/phpinfo.php',
        '/vendor/phpunit/phpunit/src/util/php/eval-stdin.php',
        '/actuator',
        '/wp-admin',
        '/_profiler/phpinfo',
        '/debug/default/view',
        '/server-status',
        '/server-info',
    ],
    // You may add 'curl/' or 'python-requests' here, but note they are used
    // by many legitimate API clients and may cause false positives.
    'bad_user_agents' => [
        'sqlmap',
        'acunetix',
        'nuclei',
        'masscan',
        'dirbuster',
        'nikto',
        'nessus',
        'zgrab',
    ],
    'files' => [
        'max_files' => 12,
        'max_filename_length' => 180,
        'max_total_size' => 10485760,
        'content_inspection' => true,
        'suspicious_extensions' => [
            'php',
            'phtml',
            'phar',
            'jsp',
            'jspx',
            'asp',
            'aspx',
            'cgi',
            'pl',
            'sh',
            'bash',
            'ps1',
            'exe',
        ],
        'suspicious_mime_types' => [
            'application/x-httpd-php',
            'application/x-php',
            'text/x-php',
            'application/x-sh',
            'application/x-msdownload',
            'application/x-dosexec',
        ],
    ],
    'normalizers' => [
        'url_decode_passes' => 3,
        'html_entity_decode' => true,
        'base64_probe' => true,
    ],
    'response' => [
        'status' => 403,
        'headers' => [
            'content-type' => 'application/json; charset=utf-8',
            'cache-control' => 'no-store',
        ],
        'body' => [
            'code' => 403,
            'message' => 'Request blocked by WAF.',
        ],
    ],
    'logging' => [
        'enabled' => true,
        'channel' => null,
        'body_max_length' => 2048,
        'ua_max_length' => 255,
        'matched_sample_length' => 120,
    ],
    'rules' => [
        [
            'rule_id' => 'sqli-union-select',
            'name' => 'SQL UNION SELECT probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/\\bunion\\b.{0,64}\\bselect\\b/is',
            'prefilters' => ['union', 'select'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-select-from',
            'name' => 'SQL SELECT FROM probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/\\bselect\\b.{0,64}\\bfrom\\b/is',
            'prefilters' => ['select', 'from'],
            'score' => 50,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-tautology',
            'name' => 'SQL tautology payload',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/(?:\\bor\\b|\\band\\b)\\s+[\\(\\s]*[\\\'"]?\\d+[\\\'"]?\\s*=\\s*[\\\'"]?\\d+[\\\'"]?/i',
            'prefilters' => ['or', 'and', '='],
            'score' => 45,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-tautology-string',
            'name' => 'SQL string tautology payload',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/(?:\\bor\\b|\\band\\b)\\s+[\\(\\s]*([\\\'"])[a-z0-9_ ]+\\1\\s*=\\s*([\\\'"]?)[a-z0-9_ ]+\\2/i',
            'prefilters' => ['or', 'and', '='],
            'score' => 45,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-comment',
            'name' => 'SQL comment after quote',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/[\\\'"]\\s*(?:#(?:\\s|$)|--(?:\\s|$)|\\/\\*)/',
            'prefilters' => ["'", '"'],
            'score' => 40,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-time-based',
            'name' => 'SQL time-based blind probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/(?:\\bsleep\\s*\\(\\s*\\d|\\bbenchmark\\s*\\(\\s*\\d|\\bwaitfor\\s+delay\\b|\\bpg_sleep\\s*\\(|\\bdbms_pipe\\.receive_message\\b|\\bsys\\.delay\\s*\\()/i',
            'prefilters' => ['sleep', 'benchmark', 'waitfor', 'pg_sleep', 'dbms_pipe', 'sys.delay'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-stacked-query',
            'name' => 'SQL stacked query probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/(?:;|\\r|\\n)\\s*(?:drop|delete|truncate|alter|create|insert|update)\\s+(?:table|database|index|view|into|from|or\\b|user|set)/i',
            'prefilters' => ['drop', 'delete', 'truncate', 'alter', 'insert', 'update', 'create'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-boolean-evasion',
            'name' => 'SQL boolean tautology evasion',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/(?:\\bor\\b|\\band\\b)\\s+[\\\'"]?(?:true|false)\\b\\s*(?:#|--|$|\\)|[\\\'"])|(?:\\bor\\b|\\band\\b)\\s+[\\\'"]?[\\w]+[\\\'"]?\\s*(?:<>|!=|<=|>=|<|>)\\s*[\\\'"]?[\\w]+[\\\'"]?\\s*(?:#|--|$)|(?:\\bor\\b|\\band\\b)\\s+[\\\'"]?[\\w]+[\\\'"]?\\s+like\\s+[\\\'"]?[\\w]+[\\\'"]?/i',
            'prefilters' => ['or', 'and', 'like', 'true', 'false', '<>', '!='],
            'score' => 45,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-structure-probe',
            'name' => 'SQL structure enumeration probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/\\bhaving\\s+[\\\'"]?\\d+[\\\'"]?\\s*=\\s*[\\\'"]?\\d+|\\border\\s+by\\s+\\d+\\s*(?:#|--)|\\bgroup\\s+by\\s+.{0,32}\\bhaving\\b/i',
            'prefilters' => ['having', 'order by', 'group by'],
            'score' => 45,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-error-based',
            'name' => 'SQL error-based extraction probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/\\b(?:extractvalue|updatexml)\\s*\\(|\\bfloor\\s*\\(\\s*rand\\s*\\(/i',
            'prefilters' => ['extractvalue', 'updatexml', 'floor(rand'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-blind-functions',
            'name' => 'SQL blind injection function chain',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/(?:ascii|ord)\\s*\\(\\s*(?:substr|substring|mid|left|right)\\s*\\(|\\b(?:user|database)\\s*\\(\\s*\\)|\\bif\\s*\\(\\s*[\\\'"]?\\d+[\\\'"]?\\s*=|\\bcase\\s+when\\s+.{0,64}\\bthen\\b/i',
            'prefilters' => ['ascii', 'ord', 'substr', 'substring', 'mid', 'left', 'right', 'user', 'database', 'if', 'case when'],
            'score' => 50,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-file-operations',
            'name' => 'SQL file read/write attempt',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/\\binto\\s+(?:out|dump)file\\b|\\bload_file\\s*\\(/i',
            'prefilters' => ['outfile', 'dumpfile', 'load_file'],
            'score' => 70,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-system-schema',
            'name' => 'SQL system schema access probe',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/information_schema|mysql\\.user|pg_catalog|sqlite_master/i',
            'prefilters' => ['information_schema', 'mysql.user', 'pg_catalog', 'sqlite_master'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'sqli-oracle-concat',
            'name' => 'SQL string concatenation injection',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/(?:[\\\'"]\\s*\\|\\||\\|\\|\\s*[\\\'"])\\s*\\(?\\s*(?:select|nvl|chr|decode|trim|utl_inaddr|utl_http)/i',
            'prefilters' => ['||'],
            'score' => 50,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'nosql-mongo-operator',
            'name' => 'NoSQL operator injection',
            'type' => 'nosql',
            'target' => 'input',
            'pattern' => '/\\$(?:ne|eq|gt|gte|lt|lte|in|nin|or|and|not|where|regex|exists|type|mod|all|size|elemMatch)\\b/i',
            'prefilters' => ['$'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'xxe-external-entity',
            'name' => 'XML external entity injection',
            'type' => 'xxe',
            'target' => 'input',
            'pattern' => '/<!ENTITY[^>]*SYSTEM|<!DOCTYPE[^>\\]]*\\[[^\\]]*<!ENTITY/is',
            'prefilters' => ['<!entity', '<!doctype'],
            'score' => 70,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'log4shell-jndi',
            'name' => 'JNDI lookup injection',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/\\$\\{\\s*(?:jndi|env|sys)\\s*:/i',
            'prefilters' => ['${'],
            'score' => 65,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'php-deserialize-payload',
            'name' => 'PHP serialized object payload',
            'type' => 'deserialization',
            'target' => 'input',
            'pattern' => '/(?:O:\\d+:"|C:\\d+:"|[aN]:\\d+:\\{|R:\\d+)/',
            'prefilters' => ['O:', 'C:', 'a:', 'N;', 'R:'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'crlf-header-injection',
            'name' => 'CRLF header injection payload',
            'type' => 'header',
            'target' => 'input',
            'pattern' => '/(?:\\r\\n|\\n|%0d%0a|%0a)(?:set-cookie|location|refresh|content-type|content-length|authorization)\\s*:/i',
            'prefilters' => ['set-cookie', 'location', 'refresh', 'content-type', 'content-length', 'authorization', '%0d%0a', '%0a'],
            'score' => 50,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'xss-script-tag',
            'name' => 'Script tag payload',
            'type' => 'xss',
            'target' => 'input',
            'pattern' => '/<\\s*script\\b/i',
            'prefilters' => ['<', '&lt;'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'xss-event-handler',
            'name' => 'Inline event handler payload',
            'type' => 'xss',
            'target' => 'input',
            'pattern' => '/<[a-z][^>]{0,300}?\\s+on[a-z]{2,30}\\s*=\\s*[^\\s>]/is',
            'prefilters' => ['<'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'xss-dangerous-scheme',
            'name' => 'Dangerous URI scheme',
            'type' => 'xss',
            'target' => 'input',
            'pattern' => '/(?:j\\s*a\\s*v\\s*a\\s*s\\s*c\\s*r\\s*i\\s*p\\s*t|v\\s*b\\s*s\\s*c\\s*r\\s*i\\s*p\\s*t)\\s*:|d\\s*a\\s*t\\s*a\\s*:\\s*(?:text\\/html|application\\/xhtml|image\\/svg)/i',
            'prefilters' => ['jav', '&#106', '&#x6a', 'vbscript', 'data:', '&#100', '&#x64'],
            'score' => 45,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'rce-shell-metachar',
            'name' => 'Shell metacharacter chain',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/(?:;|\\|\\||&&|`|\\$\\().{0,48}(?:curl|wget|bash|sh|python|perl|nc)\\b/is',
            'prefilters' => [';', '||', '&&', '`', '$(', 'curl', 'wget', 'bash', 'sh'],
            'score' => 70,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'rce-command-injection',
            'name' => 'Command injection probe',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/(?:;|\\||`|\\$\\(|\\r|\\n|&&|\\|\\|)\\s*(?:whoami|uname|certutil|powershell|nslookup|ifconfig|ipconfig|netstat|tasklist|wget|curl|bash|python|perl|ruby|nc|netcat|chmod|chown|mshta|bitsadmin|netsh|wscript|cscript|msiexec|net\\s+user|reg\\s+add)\\b/i',
            'prefilters' => ['whoami', 'uname', 'certutil', 'powershell', 'nslookup', 'ifconfig', 'ipconfig', 'netstat', 'tasklist', 'wget', 'curl', 'bash', 'python', 'perl', 'ruby', 'nc', 'netcat', 'chmod', 'chown', 'mshta', 'bitsadmin', 'netsh', 'wscript', 'cscript', 'msiexec', 'net user', 'reg add'],
            'score' => 50,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'rce-reverse-shell',
            'name' => 'Reverse shell payload',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/\\/dev\\/tcp\\/|\\b(?:nc|ncat)\\b[^\\r\\n]{0,64}\\s-e\\b|\\b(?:ba|z|da)sh\\s+-i\\b|\\bsocat\\b[^\\r\\n]{0,64}\\bexec:|python[23]?\\s+-c\\b[^\\r\\n]{0,32}(?:import\\s+socket|subprocess|__import__)/i',
            'prefilters' => ['/dev/tcp', 'nc', 'ncat', '-i', '-e', 'socat', '-c '],
            'score' => 70,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'php-code-execution',
            'name' => 'PHP code execution string',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/\\beval\\s*\\(|\\bassert\\s*\\(|\\bsystem\\s*\\(|\\bshell_exec\\s*\\(|\\bpassthru\\s*\\(|\\bpopen\\s*\\(|\\bproc_open\\s*\\(|create_function\\s*\\(|call_user_func(?:_array)?\\s*\\(.{0,64}\\b(?:assert|eval)\\b\\s*[,(]|preg_replace\\s*\\(.{0,64}[\\\'"]\\/[a-z.*]*\\/[a-z]*e[\\\'"]\\s*,/is',
            'prefilters' => ['eval', 'assert', 'system', 'shell_exec', 'passthru', 'popen', 'proc_open', 'create_function', 'call_user_func', 'preg_replace'],
            'score' => 50,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'ssrf-dangerous-scheme',
            'name' => 'Dangerous network URI scheme',
            'type' => 'ssrf',
            'target' => 'input',
            'pattern' => '/(?:gopher|dict|tftp|ldaps?|jar|netdoc|glob):\\/\\//i',
            'prefilters' => ['gopher', 'dict:', 'tftp', 'ldap', 'jar:', 'netdoc', 'glob:'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'credential-leak',
            'name' => 'Credential material in request',
            'type' => 'leak',
            'target' => 'input',
            'pattern' => '/(?:AKIA|ASIA)[0-9A-Z]{16}|LTAI[0-9A-Za-z]{12,}|AKID[0-9A-Za-z]{10,}|STS\\.[0-9A-Za-z]{10,}|-----BEGIN [A-Z ]*PRIVATE KEY-----|sk_live_[0-9a-zA-Z]{10,}|ghp_[0-9A-Za-z]{20,}|xox[baprs]-[0-9A-Za-z-]{10,}/',
            'prefilters' => ['akia', 'asia', 'ltai', 'akid', 'sts.', 'private key', 'sk_live_', 'ghp_', 'xox'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'jwt-alg-none',
            'name' => 'JWT unsigned algorithm token',
            'type' => 'auth',
            'target' => 'input',
            'pattern' => '/"alg"\\s*:\\s*"?\\s*none|eyJhbGciOiJub25l/i',
            'prefilters' => ['"alg"', 'alg:', 'none', 'eyjhb'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'ssti-template-exploit',
            'name' => 'Template injection exploit payload',
            'type' => 'ssti',
            'target' => 'input',
            'pattern' => '/\\{\\{[^{}]{0,200}__(?:class|subclasses|mro|globals|builtins|init)[^{}]{0,200}\\}\\}|\\{%[^%]{0,200}(?:__|import\\s|config|self\\.)[^%]{0,200}%\\}|<#assign|freemarker\\.template\\.utility|\\$\\{[^}]{0,100}(?:getRuntime|ProcessBuilder|exec\\()/i',
            'prefilters' => ['{{', '{%', '<#assign', 'freemarker', '${'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'deserialization-java',
            'name' => 'Java deserialization payload',
            'type' => 'deserialization',
            'target' => 'input',
            'pattern' => '/rO0AB|"@type"\\s*:\\s*"(?:com\\.|org\\.apache|javax\\.|net\\.sf|java\\.|sun\\.)|\\bObjectInputStream\\b|\\breadObject\\s*\\(/i',
            'prefilters' => ['ro0ab', '@type', 'objectinputstream', 'readobject'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'proto-pollution',
            'name' => 'Prototype pollution payload',
            'type' => 'injection',
            'target' => 'input',
            'pattern' => '/__proto__|constructor\\s*\\.\\s*constructor|\\[\\s*[\\\'"]constructor[\\\'"]\\s*\\]|__defineGetter__|__lookupGetter__/i',
            'prefilters' => ['__proto__', 'constructor', '__definegetter__', '__lookupgetter__'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'thinkphp-rce-param',
            'name' => 'ThinkPHP filter overwrite payload',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/(?:^|[=&_])__construct\\b|filter\\]?\\]?\\s*=\\s*(?:system|assert|phpinfo|eval|call_user_func)/i',
            'prefilters' => ['__construct', 'filter'],
            'score' => 75,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'framework-exploit-input',
            'name' => 'Known framework exploit signature in input',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/invokefunction|think\\\\app|wls-wsat|bsh\\.servlet|JMXInvokerServlet|getdata\\.jsp/i',
            'prefilters' => ['invokefunction', 'think', 'wls-wsat', 'bsh.servlet', 'jmxinvokerservlet', 'getdata.jsp'],
            'score' => 65,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'ognl-struts',
            'name' => 'OGNL expression injection',
            'type' => 'rce',
            'target' => 'input',
            'pattern' => '/%\\{\\s*#|\\$_memberAccess|#context\\[|\\((?:#|@).{0,32}\\).{0,32}(?:getRuntime|exec|process)/i',
            'prefilters' => ['%{', '_memberaccess', '#context', '#', 'exec', 'getruntime', '@java'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'orm-operator-injection',
            'name' => 'ORM operator injection payload',
            'type' => 'sqli',
            'target' => 'input',
            'pattern' => '/"[\\w]+"\\s*:\\s*"(?:EXP|GT|GTE|LT|LTE|NEQ|BETWEEN)"\\s*[,}]/',
            'prefilters' => ['"exp"', '"gt"', '"gte"', '"lt"', '"lte"', '"neq"', '"between"'],
            'score' => 40,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'null-byte-param',
            'name' => 'Null byte in parameter value',
            'type' => 'evasion',
            'target' => 'input',
            'pattern' => '/%00|\\x00/',
            'prefilters' => ['%00', "\0"],
            'score' => 30,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'path-framework-exploit',
            'name' => 'Known framework exploit path probe',
            'type' => 'path',
            'target' => 'path',
            'pattern' => '/(?:invokefunction|call_user_func_array\\)|think\\\\app|wls-wsat|bsh\\.servlet|jmx-console|JMXInvokerServlet|wpsAssistServlet|htmlofficeservlet|XmlRpcServlet|\\/druid\\/|debug\\/pprof|xmlrpc\\.php|wp-json\\/wp\\/v2\\/users|\\/runtime\\/log|FCKeditor|ewebeditor|install\\/index\\.php\\.bak)/i',
            'prefilters' => ['invokefunction', 'think', 'wls-wsat', 'bsh.servlet', 'jmx-console', 'jmxinvokerservlet', 'wpsassistservlet', 'htmlofficeservlet', 'xmlrpcservlet', '/druid/', 'debug/pprof', 'xmlrpc.php', 'wp-json', 'runtime/log', 'fckeditor', 'ewebeditor', 'install/index.php.bak'],
            'score' => 85,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'llm-prompt-override',
            'name' => 'LLM prompt injection instruction override',
            'type' => 'llm',
            'target' => 'input',
            'pattern' => '/(?:ignore|disregard|forget|忽略|无视|忘记)\\s+(?:all\\s+)?(?:any\\s+)?(?:previous|prior|above|earlier|之前|之前所有|以上|上述)\\s*(?:instructions?|prompts?|rules?|directives?|constraints?|指示|指令|规则|约束)?/i',
            'prefilters' => ['ignore', 'disregard', 'forget', '忽略', '无视', '忘记'],
            'score' => 40,
            'action' => 'score',
            'enabled' => false,
        ],
        [
            'rule_id' => 'llm-system-prompt-probe',
            'name' => 'LLM system prompt disclosure probe',
            'type' => 'llm',
            'target' => 'input',
            'pattern' => '/(?:system\\s+prompt|reveal\\s+(?:your|the)\\s+(?:instructions?|system)|show\\s+(?:your|me\\s+your)\\s+(?:system|initial)|DAN\\s+mode|developer\\s+mode|jailbreak|系统提示|你的?初始|展示你的?系统)/i',
            'prefilters' => ['system prompt', 'reveal your', 'show your', 'show me your', 'dan mode', 'developer mode', 'jailbreak', '系统提示', '初始'],
            'score' => 40,
            'action' => 'score',
            'enabled' => false,
        ],
        [
            'rule_id' => 'llm-forged-approval',
            'name' => 'LLM forged intermediate approval marker',
            'type' => 'llm',
            'target' => 'input',
            'pattern' => '/(?:observation|approval|authorization)\\s*:\\s*(?:granted|approved|yes|true)|管理员已(?:批准|通过)|已(?:获得|通过)(?:审批|批准)/i',
            'prefilters' => ['observation:', 'approval:', 'authorization:', '管理员已', '已获得', '已通过'],
            'score' => 40,
            'action' => 'score',
            'enabled' => false,
        ],
        [
            'rule_id' => 'traversal-dot-dot',
            'name' => 'Path traversal sequence',
            'type' => 'traversal',
            'target' => 'input',
            'pattern' => '/\\.\\.(?:[\\/\\\\;]|%2f|%5c|%3b)|%2e%2e(?:%2f|%5c|%3b)|%252e/i',
            'prefilters' => ['..', '%2e', '%252e'],
            'score' => 65,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'lfi-sensitive-file',
            'name' => 'Sensitive local file inclusion path',
            'type' => 'lfi',
            'target' => 'input',
            'pattern' => '/(?:\\/etc\\/(?:passwd|shadow|hosts|issue|nginx)|\\/proc\\/self\\/(?:environ|cwd)|id_rsa|\\.ssh\\/|web\\.config|boot\\.ini|win\\.ini|\\.aws\\/credentials)/i',
            'prefilters' => ['/etc/', 'passwd', 'shadow', '/proc/', 'id_rsa', '.ssh', 'web.config', 'boot.ini', 'win.ini', '.aws'],
            'score' => 75,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'lfi-php-stream-wrapper',
            'name' => 'PHP stream wrapper file inclusion',
            'type' => 'lfi',
            'target' => 'input',
            'pattern' => '/php:\\/\\/(?:filter|input|expect|phar|data|zip|compress\\.zlib)/i',
            'prefilters' => ['php://'],
            'score' => 75,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'ssrf-metadata',
            'name' => 'SSRF cloud metadata probe',
            'type' => 'ssrf',
            'target' => 'input',
            'pattern' => '/(?:169\\.254\\.169\\.254|100\\.100\\.100\\.200|metadata\\.google\\.internal|metadata\\.tencentyun\\.com|fd00:ec2::254|\\/openstack\\/latest\\/securitykey|\\/metadata\\/identity\\/oauth2\\/token|localhost(?::\\d+)?|127\\.0\\.0\\.1)/i',
            'prefilters' => ['169.254.169.254', '100.100.100.200', 'metadata.google.internal', 'metadata.tencentyun.com', 'fd00:ec2', 'openstack', 'oauth2/token', 'localhost', '127.0.0.1'],
            'score' => 60,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'ssrf-alt-loopback',
            'name' => 'SSRF alternate loopback encoding',
            'type' => 'ssrf',
            'target' => 'input',
            'pattern' => '/(?:::1(?![0-9])|0\\.0\\.0\\.0|\\b127(?:\\.\\d{1,3}){1,3}\\b|0x7f[0-9a-f]{0,6}\\b|\\b2130706433\\b|\\b0177(?:\\.\\d{1,3}){0,2}\\.1\\b|\\[::ffff:)/i',
            'prefilters' => ['::1', '0.0.0.0', '127.', '0x7f', '2130706433', '0177', '::ffff'],
            'score' => 55,
            'action' => 'score',
            'enabled' => true,
        ],
        [
            'rule_id' => 'path-sensitive-probe',
            'name' => 'Sensitive path probe',
            'type' => 'path',
            'target' => 'path',
            'pattern' => '/(?:\\.env|\\.git\\/config|\\.git\\/head|\\.svn|\\.ds_store|\\.htaccess|\\.htpasswd|phpinfo\\.php|actuator|wp-admin|_profiler|debug\\/default\\/view|server-status|server-info)/i',
            'prefilters' => ['.env', '.git/config', '.git/head', '.svn', '.ds_store', '.htaccess', '.htpasswd', 'phpinfo.php', 'actuator', 'wp-admin', '_profiler', 'debug/default/view', 'server-status', 'server-info'],
            'score' => 85,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'ua-scanner',
            'name' => 'Known scanner user agent',
            'type' => 'ua',
            'target' => 'ua',
            'pattern' => '/(?:sqlmap|acunetix|nuclei|masscan|nessus|nikto|dirbuster)/i',
            'prefilters' => ['sqlmap', 'acunetix', 'nuclei', 'masscan', 'nessus', 'nikto', 'dirbuster'],
            'score' => 65,
            'action' => 'block',
            'enabled' => true,
        ],
        [
            'rule_id' => 'header-proxy-inject',
            'name' => 'Suspicious forwarding header payload',
            'type' => 'header',
            'target' => 'header',
            'pattern' => '/(?:\\bforwarded\\b|\\bx-forwarded-for\\b).{0,24}(?:127\\.0\\.0\\.1|169\\.254\\.169\\.254)/i',
            'prefilters' => ['forwarded', 'x-forwarded-for', '127.0.0.1', '169.254.169.254'],
            'score' => 40,
            'action' => 'score',
            'enabled' => true,
        ],
    ],
];
